### ISSUE TITLE
`profile.release` is missing

### ISSUE THREAD

**Issue by cedeber** [leptos-rs/start-axum-0.6#17]
`profile.wasm-release` inherits from `release` but `profile.release` is not set.

Wouldn't be `Cargo.toml` look like this instead?
```toml
[profile.release]
lto = true        # Enable link-time optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
panic = "abort"   # Abort on panic
strip = true      # Strip symbols from binary

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = "z"      # Optimize for size
```

It allows to have `start-axum` from 9MB to 4.1MB on my M1.
`strip=true` will be also very useful for linux users as the debug symbols are embedded in the binary, unlike on Windows or Mac. And it's also MB of data.
